import type { Metadata } from "next";

import { Montserrat } from "next/font/google";
import Header from "@/components/nav/Header";
import "./globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { Toaster } from "@/components/ui/toaster";

const montserrat = Montserrat({
  weight: ["300", "500", "700"],
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased min-h-screen relative flex flex-col justify-between w-full`}
      >
        <Toaster />
        <Header />
        <main className="flex-1 min-h-full">{children}</main>
      </body>
    </html>
  );
}
